### PR TITLE
Bump minimum LibExpat for 0.6

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by musm** [comment]
Should fix https://github.com/JuliaPackaging/WinRPM.jl/issues/88

**Comment by yuyichao** [comment]
I don't think we do this

**Comment by tkelman** [comment]
this version is not required on release

**Comment by musm** [comment]
Minimums are only for the latest release version of julia?

**Comment by tkelman** [comment]
they're applied across all julia versions the package supports

**Comment by musm** [comment]
If I understand correctly, minimums in the REQUIRE doesn't necessarily mean minimum working version on _all__ version of Julia, just the minimum version required on the  lowest version supported with the package?

**Comment by tkelman** [comment]
yes. what was in 0.2.4 that you're wanting to require?

#88 was probably already fixed by the libexpat tags

**Comment by musm** [comment]
> yes. what was in 0.2.4 that you're wanting to require?


Specifically this PR : https://github.com/JuliaIO/LibExpat.jl/pull/56 
which fixes the LibExpat bug that was causing issues in  https://github.com/JuliaPackaging/WinRPM.jl/issues/88

**Comment by tkelman** [comment]
and that was not necessary on julia 0.5

**Pull request closed without merging**
