### PR TITLE
Remove help function

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by musm** [comment]
```julia
@deprecate help() "Please see the README.md file at https://github.com/JuliaPackaging/WinRPM.jl"
```
What if I add the above?  Would that be acceptable.
@ararslan @tkelman

**Comment by ararslan** [comment]
Yes, I think that's a good deprecation.

**Comment by musm** [comment]
I had to open the PR at https://github.com/JuliaPackaging/WinRPM.jl/pull/131
since in this PR it says `unknown repository` for some reason

**Comment by ararslan** [comment]
Huh, weird.

**Pull request closed without merging**
