### PR TITLE
Add Julia 1.0 compatibility changes.

### PR DESCRIPTION
**Pull request by hessammehr**
Basically change `warn` to `@warn` and migrate iterators to the new format.

### CODE REVIEW

**Comment by musm** [comment]
LGTM, someone should also release a tagged version after this PR is merged.

**Comment by davidanthoff** [comment]
Can someone merge this and tag?

**Comment by musm** [comment]
cc @ararslan @nalimilan @tkelman

**Comment by musm** [comment]
basically any packages that depend on Winrpm, like hdf5, do not build on Julia 1.0

**Comment by hessammehr** [comment]
@nalimilan `WinRPM.update` and `WinRPM.install` work fine on my computer.

**Comment by musm** [comment]
```julia
(v1.0) pkg> build HDF5
  Building LibCURL ─→ `C:\Users\Mus\.julia\packages\LibCURL\Qs5og\deps\build.log`
  Building WinRPM ──→ `C:\Users\Mus\.julia\dev\WinRPM\deps\build.log`
 Resolving package versions...
┌ Error: Error building `WinRPM`:
│ ERROR: LoadError: InitError: "ErrorException(\"Error parsing document : 0\"), syntax error, 1, 1, 1"
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] xp_parse(::String) at C:\Users\Mus\.julia\packages\LibExpat\6jLDP\src\LibExpat.jl:240
│  [3] update(::Bool, ::Bool) at C:\Users\Mus\.julia\dev\WinRPM\src\WinRPM.jl:167
│  [4] __init__() at C:\Users\Mus\.julia\dev\WinRPM\src\WinRPM.jl:46
│  [5] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:627
│  [6] _require_from_serialized(::String) at .\loading.jl:678
│  [7] _require(::Base.PkgId) at .\logging.jl:317
│  [8] require(::Base.PkgId) at .\loading.jl:852
│  [9] macro expansion at .\logging.jl:311 [inlined]
│  [10] require(::Module, ::Symbol) at .\loading.jl:834
│  [11] top-level scope at C:\Users\Mus\.julia\dev\WinRPM\deps\build.jl:2
│  [12] include at .\boot.jl:317 [inlined]
│  [13] include_relative(::Module, ::String) at .\loading.jl:1038
│  [14] include(::Module, ::String) at .\sysimg.jl:29
│  [15] include(::String) at .\client.jl:388
│  [16] top-level scope at none:0
│ during initialization of module WinRPM
│ in expression starting at C:\Users\Mus\.julia\dev\WinRPM\deps\build.jl:1
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1068
```

@hessammehr  have ideas with LibExpat fails here

**Comment by musm** [comment]
It looks like I had to manually delete the WinRPM cache to get things to work.

I think this PR is good to be merged.

**Comment by andreasnoack** [comment]
Indeed. I've also just been able to install HDF5.jl without problems with this PR so @nalimilan it would be great if you could merge and make a new release.

**Comment by nalimilan** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/17428. Hopefully it won't break anything. It would be really nice to have a test suite.

**Comment by andreasnoack** [comment]
Thanks

> It would be really nice to have a test suite.

Indeed. It is quite reckless that this package doesn't have tests.

**Pull request merged**
