### PR TITLE
Fix a number of julia 0.7/1.0 deprecations

### LINKED ISSUE #163: Error building `Gtk`
got this error running Julia v1.0.0 x64 upon win10 x64

Error: Error building Gtk:
│ [ Info: Multiple package candidates found for mingw64(libjpeg-8.dll), picking newest.
│ ERROR: LoadError: MethodError: no method matching length(::WinRPM.RPMVersionNumber)
│ Closest candidates are:
│ length(!Matched::Core.SimpleVector) at essentials.jl:571
│ length(!Matched::Base.MethodList) at reflection.jl:728
│ length(!Matched::Core.MethodTable) at reflection.jl:802

### PR DESCRIPTION
**Pull request by davidanthoff**
Fixes #163. And another bug.

A quick merge and new release to METADATA would be great, as this package is still broken on julia 1.0 without this.

### CODE REVIEW

**Comment by tknopp** [comment]
@davidanthoff  does Gtk build with this? That would be great!

**Comment by tknopp** [comment]
ping @ararslan and @nalimilan for @davidanthoff request to merge and release.

**Comment by nalimilan** [comment]
Thanks, I'll merge and tag since this seems simple enough.

**Comment by nalimilan** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/17622

**Comment by davidanthoff** [comment]
I didn’t test Gtk, but Cairo now seems to work.

**Comment by tknopp** [comment]
I will trigger CI once its in METADATA. Thanks for the fix David!

**Pull request merged**
