### PR TITLE
WIP/RFC: Migrate away from Zlib

### LINKED ISSUE #84: Migrate away from Zlib.jl?
I'm guessing the replacement for Zlib.jl is meant to be https://github.com/BioJulia/Libz.jl, which claims to be faster.

### PR DESCRIPTION
**Pull request by ranjanan**
This PR attempts to migrate away from Zlib.jl to its replacement Libz.jl. Fixes #84. 

Currently, not sure if this is the appropriate fix. Is there a way I can test whether this works? There's no runtests.jl file for this package too.

cc: @tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
try deleting (not Pkg.rm) packages that use this for BinDeps and reinstalling them with this branch checked out. adding appveyor here would be a good idea.

**Comment by tkelman** [comment]
also delete the winrpm cached files too so you're sure it's testing this code path

**Comment by ranjanan** [comment]
I tested on `Cbc` and `Ipopt` and this seemed to work.

**Comment by ranjanan** [comment]
This was what I did: 

1. `Pkg.add("Cbc"); Pkg.add("Ipopt")`
2. Checkout my fixes in WinRPM
3. Delete the contents of the `cache` folder
4. Delete the `Cbc` and `Ipopt` folders in my `.julia` folder
5. Run `Pkg.update()` which reinstalls both those packages with their deps. 

Things seemed to work fine. Even a print statement I put around my fix (to check if it was traversing that path) printed normally.

**Pull request merged**
