### PR TITLE
JULIA_HOME is no longer defined

### PR DESCRIPTION
**Pull request by tbeason**
JULIA_HOME is no longer defined which results in build errors. I updated usage to Compat.Sys.BINDIR.

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks! I think you need to bump the dependency on Compat to 0.41 in REQUIRE.

**Comment by tkelman** [comment]
0.42: https://github.com/JuliaLang/Compat.jl/commit/747b75ddec3eae052a7b4df1e5d19c75c0f277f8

**Comment by nalimilan** [comment]
@tkelman OK to merge?

**Comment by tkelman** [comment]
Yes, seems fine

**Pull request merged**
