### PR TITLE
Add some very basic tests

### PR DESCRIPTION
**Pull request by musm**
At a bare minimum this should be much better than no tests

### CODE REVIEW

**Comment by musm** [comment]
Someone will have to activate appveyor to have this work

**Comment by tkelman** [comment]
If this package had an uninstall capability then it would make the most sense to check whether or not these are installed already, and clean them up afterwards if they aren't

**Comment by musm** [comment]
Is there anything wrong with having at least something as basic as this  to catch out bugs that one might miss from local testing. When WinRPM has better uninstall options they can be added later?

**Comment by tkelman** [comment]
How many megabytes of stuff does this download upon Pkg.test that you might not need/want?

**Comment by tkelman** [comment]
testing is good, but if possible we should try to do so in a clean, temporary, test-only environment that we clean up afterwards

**Comment by musm** [comment]
Good point.

Unrelated
Could you merge: https://github.com/JuliaIO/JLDArchives.jl/pull/10
None of the JLDArchives PRs actually run travis without those changes

**Pull request closed without merging**
